"""update models to match db documentation

Revision ID: 13cc3b4a89bc
Revises: 4166cf92d13e
Create Date: 2025-03-29 17:07:41.102830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cc3b4a89bc'
down_revision = '4166cf92d13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_factura', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('serie_factura', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('nr_factura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valoare', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('modalitate_plata', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('furnizor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'furnizori', ['furnizor_id'], ['id'])

    # Copiere date din coloanele existente în coloanele noi pentru facturi
    op.execute("""
        UPDATE facturi 
        SET data_factura = data_emitere,
            serie_factura = serie,
            nr_factura = numar,
            valoare = valoare_totala,
            modalitate_plata = metoda_plata
    """)

    with op.batch_alter_table('furnizori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_fiscal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cont_bancar', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sold_furnizor', sa.Numeric(precision=10, scale=2), nullable=True))
        
    # Trebuie să păstrăm coloanele pentru compatibilitate cu codul existent
    # Le vom menține în baza de date pentru moment
    # batch_op.drop_column('oras')
    # batch_op.drop_column('judet')
    # batch_op.drop_column('email')

    with op.batch_alter_table('miscari_stoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comanda_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comenzi', ['comanda_id'], ['id'])

    with op.batch_alter_table('produse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pret', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('pret_achizitie',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('pret_vanzare',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('descriere')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriere', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('pret_vanzare',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('pret_achizitie',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('pret')

    with op.batch_alter_table('miscari_stoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comanda_id')

    with op.batch_alter_table('furnizori', schema=None) as batch_op:
        # Aceste coloane de fapt exista deja, doar am comentat eliminarea lor în upgrade
        # batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('judet', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('oras', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('sold_furnizor')
        batch_op.drop_column('cont_bancar')
        batch_op.drop_column('cod_fiscal')

    with op.batch_alter_table('facturi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('furnizor_id')
        batch_op.drop_column('modalitate_plata')
        batch_op.drop_column('valoare')
        batch_op.drop_column('nr_factura')
        batch_op.drop_column('serie_factura')
        batch_op.drop_column('data_factura')

    # ### end Alembic commands ###
